### PR TITLE
feat: Highlight search matches

### PR DESCRIPTION
**Pull request by e-fisher**
## Description

Highlight matched values when searching requests. Thank @allansson for laying the groundwork and extracting reusable highlight component! 🙌 I've tweaked the colors a bit to make it easier to see the highlighted parts. 

## How to Test

Test search in recorder, generator, and validator - verify matches are highlighted. 

## Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added tests for my changes.
- [ ] I have run linter locally (`npm run lint`) and all checks pass.
- [ ] I have run tests locally (`npm test`) and all tests pass.
- [x] I have commented on my code, particularly in hard-to-understand areas.

## Screenshots (if appropriate):
screencapture 2024-11-28 at 12 17 29

screencapture 2024-11-28 at 12 17 19

## Related PR(s)/Issue(s)

Resolves https://github.com/grafana/k6-studio/issues/322

### CODE REVIEW

**Review by cristianoventura — DISMISSED** [review]
Awesome! 🙌

**Comment by Llandy3d** [comment]
I was testing it out and noticed this match, is it supposed to match that first entry ? 🤔 

image

**Comment by e-fisher** [comment]
> I was testing it out and noticed this match, is it supposed to match that first entry ? 🤔
> 
> image

Yeah, that's the "fuzziness", perhaps we don't need it to be this loose in this context, I'll lower the threshold

**Review by cristianoventura — APPROVED** [review]

**Review by Llandy3d — APPROVED** [review]
🚀

**Pull request merged**
