### PR TITLE
feat: Documentation link

### PR DESCRIPTION
**Pull request by going-confetti**
## Description

* New dropdown menu in the bottom left corner that groups both the documentation link and the linkt to github issues
* Documentation option in the Help menu

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have added tests for my changes.
- [ ] I have run linter locally (`npm run lint`) and all checks pass.
- [ ] I have run tests locally (`npm test`) and all tests pass.
- [ ] I have commented on my code, particularly in hard-to-understand areas.

## Screenshots (if appropriate):
image
image

### CODE REVIEW

**Review by cristianoventura — DISMISSED** [review]
👌

**Review by Llandy3d — COMMENTED** [review]
Noticed a small bug where after selecting the icon and clicking away it stays highlighted
image

I wonder if it makes sense to have them grouped here or they should be distinct 🤔  (or just find docs under the help section)

**Comment by going-confetti** [comment]
> Noticed a small bug where after selecting the icon and clicking away it stays highlighted image

This is not a bug, it's by design, so that the focus isn't lost. It works the same in other places across the app.

> I wonder if it makes sense to have them grouped here or they should be distinct 🤔 (or just find docs under the help section)

What would be the downside of grouping them together? We discussed this with Maja and it seemed like a good solution, but maybe we're missing something

**Comment by Llandy3d** [comment]
> What would be the downside of grouping them together? We discussed this with Maja and it seemed like a good solution, but maybe we're missing something

Might just be personal opinion (and not on the strong side), the first impact was that we were now hiding the `report issue` button behind a generic info button and another detail is that there is no tooltip, so you don't know what happens until you press the button, but this button behaves differently from the others, where the others do an action and this one doesn't. (and the user cannot possibly know that 🤔 )

> This is not a bug, it's by design, so that the focus isn't lost. It works the same in other places across the app.
I feel like here seems odd to have focus on a button 🤔 
But regardless I think we have a bug because if you press on the `theme toggle` and then try to press again on this new info button, it's not going to be highlighted anymore! 😄

**Comment by going-confetti** [comment]
> But regardless I think we have a bug because if you press on the theme toggle and then try to press again on this new info button, it's not going to be highlighted anymore! 😄

Still not a bug. This is because of the difference between `:focus` and `:focus-visible` in CSS. The idea is that you may want to only have focus outlines when interacting with controls with keyboard or setting focus programmatically.
For example, when you edit a comment on GitHub, you can tab into the `B` button to make the text bold - the outline will be displayed, but will disappear if you click on any other button with your mouse cursor

**Review by cristianoventura — DISMISSED** [review]

**Review by Llandy3d — DISMISSED** [review]
LGTM!

**Review by Llandy3d — APPROVED** [review]
🚀

**Pull request merged**
